apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanos-auth
  namespace: sanosysalvos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanos-auth
  template:
    metadata:
      labels:
        app: sanos-auth
    spec:
      containers:
        - name: auth
          image: 053760945279.dkr.ecr.us-east-1.amazonaws.com/sanos-auth-serv:v2
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: DATABASE_URL_AUTH
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: SECRET_KEY_AUTH
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: USUARIOS_SERVICE_URL
              value: "http://sanos-usuarios:8000/api/usuarios/"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sanos-auth
  namespace: sanosysalvos
spec:
  selector:
    app: sanos-auth
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
