apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanos-notificaciones
  namespace: sanosysalvos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanos-notificaciones
  template:
    metadata:
      labels:
        app: sanos-notificaciones
    spec:
      containers:
        - name: notificaciones
          image: 053760945279.dkr.ecr.us-east-1.amazonaws.com/sanos-notificaciones-serv:v2
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: DATABASE_URL_NOTIFICACIONES
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: SECRET_KEY_NOTIFICACIONES
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: REDIS_URL
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: sanos-secrets
                  key: CORS_ALLOWED_ORIGINS
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sanos-notificaciones
  namespace: sanosysalvos
spec:
  selector:
    app: sanos-notificaciones
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
