apiVersion: v1
kind: Secret
metadata:
  name: sanos-secrets
  namespace: sanosysalvos
type: Opaque
stringData:
  DB_PASSWORD: "SanosPass123!"
  SECRET_KEY_USUARIOS: "django-insecure-j&u5@zk9ocobq=nm4@oupw5aysf#qf9mtcf2i8ed9wz#g0u169"
  SECRET_KEY_AUTH: "django-insecure-5hg^o8$c=1x2e^5&^bwi!m^#c%wwq0blw8=t!%2#26=$m_-o8z"
  SECRET_KEY_MASCOTAS: "django-insecure-9r(phs01ypenv7j(g*+x9q*zrla@oe(bpkad+cc!r(+l-r=gk("
  SECRET_KEY_BFF: "django-insecure-4lb_lilajp_w*zknccjx5%3gtj$^rvq0wc8zelod^o&p6@-gg@"
  SECRET_KEY_NOTICIAS: "django-insecure-@desijxc#x*&vj519g0mbxn5sw&c!%vbd&bv+^5l$nkpsq4+k-"
  SECRET_KEY_NOTIFICACIONES: "django-insecure-notificaciones-sanos-y-salvos-local"
  DATABASE_URL_USUARIOS: "postgresql://sanos_admin:SanosPass123!@sanos-usuarios-db.c9oo6visqpir.us-east-1.rds.amazonaws.com:5432/user_db?sslmode=require"
  DATABASE_URL_AUTH: "postgresql://sanos_admin:SanosPass123!@sanos-auth-db.c9oo6visqpir.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  DATABASE_URL_MASCOTAS: "postgresql://sanos_admin:SanosPass123!@sanos-mascotas-db.c9oo6visqpir.us-east-1.rds.amazonaws.com:5432/mascotas_db?sslmode=require"
  DATABASE_URL_NOTICIAS: "postgresql://sanos_admin:SanosPass123!@sanos-noticias-db.c9oo6visqpir.us-east-1.rds.amazonaws.com:5432/noticias_db?sslmode=require"
  DATABASE_URL_NOTIFICACIONES: "postgresql://sanos_admin:SanosPass123!@sanos-notificaciones-db.c9oo6visqpir.us-east-1.rds.amazonaws.com:5432/notificaciones_db?sslmode=require"
  CORS_ALLOWED_ORIGINS_BFF: "http://afc3bd2abdd374558a2bf797642b728b-69770617.us-east-1.elb.amazonaws.com"
  CORS_ALLOWED_ORIGINS_NOTIF: "http://afc3bd2abdd374558a2bf797642b728b-69770617.us-east-1.elb.amazonaws.com"